---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Assert whether restic has been installed
      ansible.builtin.assert:
        that: ansible_facts['packages']['restic'] is defined
